services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CONVEX_URL: ${NEXT_PUBLIC_CONVEX_URL:-https://calm-parakeet-566.convex.cloud}
        NEXT_PUBLIC_CONVEX_SITE_URL: ${NEXT_PUBLIC_CONVEX_SITE_URL:-https://famous-mongoose-465.convex.site}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-pk_test_ZW5kbGVzcy1nYXJmaXNoLTQ2LmNsZXJrLmFjY291bnRzLmRldiQ}
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${NEXT_PUBLIC_CLERK_SIGN_IN_URL:-/sign-in}
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${NEXT_PUBLIC_CLERK_SIGN_UP_URL:-/sign-up}
    image: splitr-web:latest
    container_name: splitr_app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - PORT=3000
    restart: unless-stopped
